### ISSUE TITLE
Missing DDEV config

### ISSUE THREAD

**Issue by Morgy93** [nevercodealone/cms-symfony-sulu#110]
Hello,

the README states:

>We use DDEV for our local development.

But there is no DDEV config present.

Would you mind committing your `.ddev` folder? It has its own `.ddev/.gitignore` so that only the relevant stuff is shared.

More info: https://ddev.readthedocs.io/en/stable/users/usage/faq/#should-i-check-in-the-ddev-directory-how-about-add-ons

**Comment by rogoit** [comment]
Good point. There is a special nginx config. 

I also think there is a new working setup in DDEV for Sulu. 

I do something. Just a second.

**Comment by rogoit** [comment]
There is a gist

https://gist.github.com/nevercodealone/264dfda7ce6212db74b3d65f91a766e5
